name: zm_supplier
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #  http: 0.12.0+1
  http: ^0.12.2
  shared_preferences: any
  modal_progress_hud: ^0.1.3
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  image_picker: ^0.6.7+22
  #  image_picker_platform_interface: ^1.1.0
  flutter_dialogs: ^1.1.0
  path: ^1.7.0
  webview_flutter: ^0.3.3
  url_launcher: ^5.7.10
  pin_code_fields: ^6.1.0
  grouped_list: ^3.7.1
  intl: ^0.16.1
  carousel_slider: ^3.0.0
  mixpanel_flutter: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/icon_place_holder.png
    - assets/images/img_welcome_salmon.png
    - assets/images/ZM_logo_white.png
    - assets/images/truck.png
    - assets/images/Truck-black.png
    - assets/images/icon-tick-green.png
    - assets/images/placeholder_all.png
    - assets/images/Star_light_grey.png
    - assets/images/Star_yellow.png
    - assets/images/Sort-blue.png
    - assets/images/img_exclaimation_red.png
    - assets/images/tick_receive_big.png
    - assets/images/orders_icon.png
    - assets/images/phone-grey.png
    - assets/images/email_grey.png
    - assets/images/filter_white.png
    - assets/images/no_orders_icon.png
    - assets/images/Calendar_grey.png
    - assets/images/Location_grey.png
    - assets/images/Link_grey.png
    - assets/images/Document_blue.png

    # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SourceSansProBold
      fonts:
        - asset: assets/fonts/SourceSansPro-Bold.ttf
    - family: SourceSansProRegular
      fonts:
        - asset: assets/fonts/SourceSansPro-Regular.ttf
    - family: SourceSansProSemiBold
      fonts:
        - asset: assets/fonts/SourceSansPro-SemiBold.ttf
    - family: SourceSansProItalic
      fonts:
        - asset: assets/fonts/SourceSansPro-Italic.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
