/**
 * Created by RajPrudhviMarella on 16/Mar/2021.
 */

class Events {
  /*Login Events*/
  static final String TAP_LOGIN = "TAP_LOGIN ";
  static final String TAP_FORGOT_PASSWORD = "TAP_FORGOT_PASSWORD";
  static final String TAP_CANCEL_RESET_PASSWORD = "TAP_CANCEL_RESET_PASSWORD";
  static final String TAP_REQUEST_RESET_PASSWORD = "TAP_REQUEST_RESET_PASSWORD";
  static final String TAP_RESET_PASSWORD_EMAIL_VERIFY_CONTINUE =
      "TAP_RESET_PASSWORD_EMAIL_VERIFY_CONTINUE";
  static final String TAP_CHANGE_PASSWORD_CONTINUE =
      "TAP_CHANGE_PASSWORD_CONTINUE";

  /*DashBoard Events*/
  static final String TAP_ORDERS_TAB = "TAP_ORDERS_TAB";
  static final String TAP_DASHBOARD_NEW_ORDER = "TAP_DASHBOARD_NEW_ORDER";
  static final String TAP_DASHBOARD_VIEW_ORDERS = "TAP_DASHBOARD_VIEW_ORDERS";
  static final String TAP_DASHBOARD_VIEW_DELIVERIES =
      "TAP_DASHBOARD_VIEW_DELIVERIES";
  static final String TAP_DASHBOARD_TODAY = "TAP_DASHBOARD_TODAY";
  static final String TAP_DASHBOARD_YESTERDAY = "TAP_DASHBOARD_YESTERDAY";
  static final String TAP_DASHBOARD_DRAFT_ORDERS = "TAP_DASHBOARD_DRAFT_ORDERS";
  static final String TAP_DASHBOARD_ORDER_FOR_DETAILS =
      "TAP_DASHBOARD_ORDER_FOR_DETAILS";
  static final String TAP_DASHBOARD_SEARCH = "TAP_DASHBOARD_SEARCH";

  /*Customers Events*/
  static final String TAP_CUSTOMERS_TAB = "TAP_CUSTOMERS_TAB ";
  static final String TAP_CUSTOMERS_TAB_ALL_OUTLETS_TAB =
      "TAP_CUSTOMERS_TAB_ALL_OUTLETS_TAB";
  static final String TAP_CUSTOMERS_TAB_THIS_WEEK_OUTLETS_TAB =
      "TAP_CUSTOMERS_TAB_THIS_WEEK_OUTLETS_TAB";
  static final String TAP_CUSTOMERS_TAB_STARRED_OUTLETS_TAB =
      "TAP_CUSTOMERS_TAB_STARRED_OUTLETS_TAB";
  static final String TAP_CUSTOMERS_TAB_LAST_WEEK_OUTLETS_TAB =
      "TAP_CUSTOMERS_TAB_LAST_WEEK_OUTLETS_TAB";
  static final String TAP_CUSTOMERS_TAB_NO_RECENT_ORDERED_OUTLETS_TAB =
      "TAP_CUSTOMERS_TAB_NO_RECENT_ORDERED_OUTLETS_TAB";
  static final String TAP_CUSTOMERS_TAB_SEARCH = "TAP_CUSTOMERS_TAB_SEARCH";
  static final String TAP_CUSTOMERS_TAB_OUTLET_FOR_DETAILS =
      "TAP_CUSTOMERS_TAB_OUTLET_FOR_DETAILS";
  static final String TAP_CUSTOMERS_TAB_OUTLET_FAVOURITE =
      "TAP_CUSTOMERS_TAB_OUTLET_FAVOURITE";
  static final String TAP_CUSTOMERS_OUTLET_DETAILS_FAVOURITE =
      "TAP_CUSTOMERS_OUTLET_DETAILS_FAVOURITE";
  static final String TAP_CUSTOMERS_OUTLET_DETAILS_VIEW_ALL_ORDERS =
      "TAP_CUSTOMERS_OUTLET_DETAILS_VIEW_ALL_ORDERS";
  static final String TAP_CUSTOMERS_OUTLET_DETAILS_VIEW_ALL_INVOICES =
      "TAP_CUSTOMERS_OUTLET_DETAILS_VIEW_ALL_INVOICES";

  /*Settings Events*/
  static final String TAP_SETTINGS_TAB = "TAP_SETTINGS_TAB";
  static final String TAP_SETTINGS_TAB_PROFILE_PIC =
      "TAP_SETTINGS_TAB_PROFILE_PIC";
  static final String TAP_SETTINGS_TAB_CATALOGUE =
      "TAP_SETTINGS_TAB_CATALOGUE";
  static final String TAP_SETTINGS_TAB_CHANGE_PASSWORD =
      "TAP_SETTINGS_TAB_CHANGE_PASSWORD";
  static final String TAP_SETTINGS_TAB_CHANGE_PASSWORD_SAVE =
      "TAP_SETTINGS_TAB_CHANGE_PASSWORD_SAVE";
  static final String TAP_SETTINGS_TAB_HELP = "TAP_SETTINGS_TAB_HELP";
  static final String TAP_SETTINGS_TAB_ASK_ZEEMART =
      "TAP_SETTINGS_TAB_ASK_ZEEMART";
  static final String TAP_SETTINGS_TAB_SEND_FEEDBACK =
      "TAP_SETTINGS_TAB_SEND_FEEDBACK";
  static final String TAP_SETTINGS_TAB_TERMS_OF_USE =
      "TAP_SETTINGS_TAB_TERMS_OF_USE";
  static final String TAP_SETTINGS_TAB_PRIVACY_POLICY =
      "TAP_SETTINGS_TAB_PRIVACY_POLICY";
  static final String TAP_SETTINGS_TAB_SIGN_OUT = "TAP_SETTINGS_TAB_SIGN_OUT";
  static final String TAP_SETTINGS_TAB_SIGN_OUT_CONFIRM =
      "TAP_SETTINGS_TAB_SIGN_OUT_CONFIRM";
  static final String TAP_SETTINGS_TAB_SIGN_OUT_CANCEL =
      "TAP_SETTINGS_TAB_SIGN_OUT_CANCEL";

  /*ViewOrders Events*/
  static final String TAP_VIEW_ORDERS_SEARCH = "TAP_VIEW_ORDERS_SEARCH";
  static final String TAP_VIEW_ORDERS_ORDER_FOR_DETAILS =
      "TAP_VIEW_ORDERS_ORDER_FOR_DETAILS";

  /*Deliveries Events*/
  static final String TAP_VIEW_DELIVERIES_SEARCH =
      "TAP_VIEW_DELIVERIES_SEARCH ";
  static final String TAP_VIEW_DELIVERIES_ORDER_FOR_DETAILS =
      "TAP_VIEW_DELIVERIES_ORDER_FOR_DETAILS";

  /*OrderDetails Events*/
  static final String TAP_ORDER_DETAILS_CONTACT = "TAP_ORDER_DETAILS_CONTACT";
  static final String TAP_ORDER_DETAILS_MORE_OPTIONS =
      "TAP_ORDER_DETAILS_MORE_OPTIONS";
  static final String TAP_ORDER_DETAILS_CANCEL_ORDER =
      "TAP_ORDER_DETAILS_CANCEL_ORDER";
  static final String TAP_ORDER_DETAILS_VIEW_AS_PDF =
      "TAP_ORDER_DETAILS_VIEW_AS_PDF";
  static final String TAP_ORDER_DETAILS_REPORT_ISSUE =
      "TAP_ORDER_DETAILS_REPORT_ISSUE";
  static final String TAP_ORDER_DETAILS_CONTACT_SUPPLIER =
      "TAP_ORDER_DETAILS_CONTACT_SUPPLIER";
  static final String TAP_ORDER_DETAILS_REPEAT_ORDER =
      "TAP_ORDER_DETAILS_REPEAT_ORDER";
  static final String TAP_ORDER_DETAILS_RECEIVE_ORDER =
      "TAP_ORDER_DETAILS_RECEIVE_ORDER";
  static final String TAP_ORDER_DETAILS_ACTIVITY_HISTORY =
      "TAP_ORDER_DETAILS_ACTIVITY_HISTORY";

  /*NewOrder Events*/
  static final String TAP_NEW_ORDER_SELECT_OUTLET =
      "TAP_NEW_ORDER_SELECT_OUTLET";
  static final String TAP_NEW_ORDER_SELECT_OUTLET_SEARCH =
      "TAP_NEW_ORDER_SELECT_OUTLET_SEARCH";
  static final String TAP_MARKET_LIST_SEARCH =
      "TAP_NEW_ORDER_MARKET_LIST_SEARCH";
  static final String TAP_MARKET_LIST_ADD_SKU = "TAP_MARKET_LIST_ADD_SKU ";
  static final String TAP_MARKET_LIST_SELECT_ORDER_NOTES =
      "TAP_MARKET_LIST_SELECT_ORDER_NOTES";
  static final String TAP_MARKET_LIST_NEXT = "TAP_MARKET_LIST_NEXT";
  static final String TAP_ORDER_REVIEW_BACK = "TAP_ORDER_REVIEW_BACK";
  static final String TAP_ORDER_REVIEW_DELIVER_ON =
      "TAP_ORDER_REVIEW_DELIVER_ON";
  static final String TAP_ORDER_REVIEW_SPECIAL_REQUEST =
      "TAP_ORDER_REVIEW_SPECIAL_REQUEST";
  static final String TAP_ORDER_REVIEW_PAGE_DELETE_DRAFT =
      "TAP_ORDER_REVIEW_PAGE_DELETE_DRAFT";
  static final String TAP_ORDER_REVIEW_PLACE_ORDER =
      "TAP_ORDER_REVIEW_PLACE_ORDER";
  static final String TAP_ORDER_REVIEW_PLACE_ORDER_CONFIRM =
      "TAP_ORDER_REVIEW_PLACE_ORDER_CONFIRM";
  static final String TAP_ORDER_REVIEW_PLACE_ORDER_CANCEL =
      "TAP_ORDER_REVIEW_PLACE_ORDER_CANCEL";
  static final String TAP_CREATE_DRAFT_ORDER = "TAP_CREATE_DRAFT_ORDER";
  /*Invoices Events*/
  static final String TAP_INVOICES_SEARCH = "TAP_INVOICES_SEARCH";
  static final String TAP_INVOICES_FILTER = "TAP_INVOICES_FILTER";
  static final String TAP_INVOICES_LINKED_ORDER = "TAP_INVOICES_LINKED_ORDER";
  static final String TAP_INVOICES_VIEW_AS_PDF = "TAP_INVOICES_VIEW_AS_PDF";
}
